### ISSUE TITLE
Parsing Error - EventType - channel.created 

### ISSUE THREAD

**Issue by rjacquemin** [GetStream/stream-chat-net#37]
We have a .net backend listening event on the SQS  integration 

Through the SQS we are receiving  messages with type 
```
"type":"channel.created"
```

Throwing 
```
var json = JObject.Parse(message.Body);
var chatEvent = Event.FromJObject(json);

Error reading string. Unexpected token: StartObject. Path 'config.commands[0]'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
```

After some investigation - it is not supported in the .net client 
https://github.com/GetStream/stream-chat-net/blob/17b0a8792329ccd054798c98722448149a78cd03/src/stream-chat-net/Event.cs#L7

Also not really mentioned in the doc 
https://getstream.io/chat/docs/node/event_object

First question 
why do we receive those `channel.created` via SQS ? 

Second question
For now I just want to discard those messages
What is the best option ? 

I did a filter based on the EventType 
but if parser fails on the ChannelCreated event 
I can not filter out properly 

see below

```

        public static bool IsProcessable(this Event chatEvent)
        {
            // We dont support all type of messages
            // https://getstream.io/chat/docs/react/webhook_events/
            switch (chatEvent.Type)
            {
                case EventType.MessageNew:
                case EventType.MessageDeleted:
                case EventType.MessageUpdated:
                    return true;
            }
            return false;
        }

        public async Task ProcessMessage(QueueMessage message, CancellationToken cancellationToken)
        {
            try
            {
                var json = JObject.Parse(message.Body);
                var chatEvent = Event.FromJObject(json);

                if (chatEvent.IsProcessable())
                {
                    _log.LogDebug($"[ChatEventsWorker] Processing chat event of type [{chatEvent.Type}]");
                    var eventProcessor = _chatEventsHelper.GetEventProcessor(chatEvent.Type);
                    await eventProcessor.ProcessEvent(chatEvent);
                }
            }
            catch (Exception e)
            {
                _log.LogError(LoggingEvents.ChatEventProcessFailed, e, $"[ChatEventsWorker] Unable to process chat message because of error => {e.Message} - Body: {message.Body}");
            }
        }


```
thank in advance 

gz#11352

**Comment by shodgetts** [comment]
Hello, thanks for getting in touch. By default, we send all events in the queue. Typically customers will filter out the ones they are interested in/not interested in. That said, I'm going to ask an engineer here to check on the missing event from the .net SDK. 

-Stephen

**Comment by peterdeme** [comment]
Is this still a problem?
